# Generated by Django 4.0.6 on 2022-07-21 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('aircraft', models.CharField(max_length=128, null=True, verbose_name='Aircraft')),
                ('status', models.CharField(max_length=128, null=True, verbose_name='Status')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='Type')),
                ('info_count', models.IntegerField(default=0, verbose_name='Info Count')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Errors Count')),
                ('pre_legend', models.IntegerField(default=0, verbose_name='Pre legend')),
                ('warning', models.IntegerField(default=0, verbose_name='Warning')),
                ('paired_b', models.IntegerField(default=0, verbose_name='Paired B')),
                ('legend', models.IntegerField(default=0, verbose_name='Legend')),
                ('lower_b', models.IntegerField(default=0, verbose_name='lower B')),
                ('repeat_legend', models.IntegerField(default=0, verbose_name='Repeat Legend')),
                ('upper_a', models.IntegerField(default=0, verbose_name='Upper A')),
                ('lower_a', models.IntegerField(default=0, verbose_name='Lower A')),
                ('paired_a', models.IntegerField(default=0, verbose_name='paired A')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
