# Generated by Django 4.0.6 on 2022-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticscsvuploadedfile',
            name='file_hash',
            field=models.CharField(default=1, max_length=256, verbose_name='File Hash'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statisticscsvuploadedfile',
            name='file',
            field=models.FileField(null=True, upload_to='csv'),
        ),
    ]
