# Generated by Django 4.0.6 on 2022-07-22 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_statisticscsvuploadedfile_file_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.CharField(max_length=32, verbose_name='Priority')),
                ('type', models.CharField(max_length=32, verbose_name='Type')),
                ('aircraft', models.CharField(max_length=32, verbose_name='Aircraft')),
                ('status', models.CharField(max_length=32, verbose_name='Status')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Errors Count')),
                ('info_count', models.IntegerField(default=0, verbose_name='Info Count')),
            ],
        ),
        migrations.AddIndex(
            model_name='csvdata',
            index=models.Index(fields=['type'], name='statistics__type_de87e8_idx'),
        ),
        migrations.AddIndex(
            model_name='csvdata',
            index=models.Index(fields=['aircraft'], name='statistics__aircraf_1e1312_idx'),
        ),
        migrations.AddIndex(
            model_name='csvdata',
            index=models.Index(fields=['status'], name='statistics__status_08347e_idx'),
        ),
    ]
